### ISSUE TITLE
Feature Request: DCH Driver Selection

### ISSUE THREAD

**Issue by ljford7** [lord-carlos/nvidia-update#24]
Feature request: 

With the newer versions of Windows, you have to use the DCH driver in lieu of the standard one. Is there anyway to add it to the script so you can select it?

Thanks!

**Comment by lord-carlos** [comment]
I did not know DCH, and found this very helpful: https://nvidia.custhelp.com/app/answers/detail/a_id/4777/~/nvidia-dch%2Fstandard-display-drivers-for-windows-10-faq

So if there already is a standard driver, you can't install the DCH driver, and vice versa.
That means we need to check if the user already has a driver installed, and then figure out which version. Then download the correct one.

- [ ] Driver detection logic
- [ ] URL for new driver
- [ ] Installation and parameters for new driver (Unpack etc.)
__________________

> With the newer versions of Windows, you **have** to use the DCH driver

@ljford7 Are you sure? As in the Standard driver does not work any more?

**Comment by ljford7** [comment]
I am on Windows 10 1903 and the standard driver doesn't work anymore. You have to install the DCH version. Here is a reddit thread with some more info: https://www.reddit.com/r/nvidia/comments/broean/psa_windows_10_1903_will_push_dch_variants_of/

**Comment by lord-carlos** [comment]
> I am on Windows 10 1903 and the standard driver doesn't work anymore. 

Seems like the standard driver should still work, but if you do a fresh install, windows will install the DHC version. Which then results in the standard driver install not working any more.

**Comment by phixion** [comment]
DCH gets pushed through windows update or windows store and will make such scripts more or less obsolete since they offer a more convenient way to keep your drivers up-to-date. 

DCH drivers cannot update standard or studio drivers so there extra logic needed as in -> stop windows update, uninstall driver if those are standard or studio, install dch, start windows update (Thats ofcourse only if you want to give a choice to switch drivers)

I guess just appending **-international-dch-whql.exe**  could do the trick with getting the download link if nvidia sticks to the same releasedates and version pattern. (nevermind theres a less hacky [PR](https://github.com/lord-carlos/nvidia-update/pull/26) already

**Comment by link-webcreations** [comment]
@phixion Sorry my PR does not bring support for DCH drivers (yet :P)
The aim of this PR is:

1. Check if already installed driver is Standard or DCH
2. If DCH, exit properly the script with an info message
3. If standard, continue...

It just avoid DCH users to install a standard driver above, which can fail

**Comment by link-webcreations** [comment]
To get support of DCH drivers, is should be theoretically easy. Just switch the **dtcid** value from 0 to **1**, and then download the *-international-dch-whql.exe version.
But I cannot test it unfortunately.

**Comment by lord-carlos** [comment]
Unless Windows will be slow with updating DCH drivers, I see little to no need to implement DCH with this script. 

Or is there any reason to use DCH drivers over standart, but not through the MS store?
Would be cool if this script was not needed any more.

**Comment by lord-carlos** [comment]
I'm going to close this issue.
If there becomes a need to install the DHC driver without windows update then e can take a look at this again.
