### ISSUE TITLE
Update readme with more detailed description 

### ISSUE THREAD

**Issue by lord-carlos** [lord-carlos/nvidia-update#7]
We need an update the default readme on how to use this powershell script for users who don't come in contact with powershell on a daily basis.

**Comment by teoxoy** [comment]
Would this info suffice?
 - Intro / Description
 - How to download and run the script
 - How to configure the script

**Comment by lord-carlos** [comment]
Yes, that would be lovely. 

The problem is I don't know what's default on windows 10. Can you actually download a random script and run it? Or do you need to install something? Or white list scripts?

It would be cool if someone who has a fresh win install and never used powershell can use the readme to install the nvidia driver.

**Comment by teoxoy** [comment]
I use win 10 on a daily basis and I had no problems with the script. There is no whitelist for scripts; you can download it and run it.

**Comment by teoxoy** [comment]
Also, would you like a logo for the project?
Maybe one that says NU (from nvidia-update) in a stylized way.

**Comment by lord-carlos** [comment]
Logo would be icing on cake. Not needed. But nice to have.

**Comment by teoxoy** [comment]
I like designing logos in my spare time. :)
You can take a look at the ones I made for my opensource projects.

**Comment by teoxoy** [comment]
Btw, can you give me write access to the repo or am I asking for too much and I should stick to PRs?

**Comment by lord-carlos** [comment]
Stick to PR. Not because I don't trust you, but I like the workflow of it.

**Comment by teoxoy** [comment]
Sure. Np

**Comment by teoxoy** [comment]
Why does the script need elevated permissions?
I am trying to make the script easier to use and added parameters in my local repo.
But passing the arguments to the new elevated process is a hassle.
I just commented out the check for elevated permissions and it works fine.
Do you maybe need elevated permissions to create the scheduled task?

Edit: Nvm, I tested out the scheduled task feature and it worked without elevated permissions.

**Comment by teoxoy** [comment]
One more thing, I found a way to extract files from an archive using only powershell with no external dependencies (i.e. 7zip, WinRar). But I think it only works in Powershell v5.
Can you check what version windows 7 is on with `$PSVersionTable.PSVersion`?

Edit: Nvm, I [found out](https://www.microsoft.com/en-us/download/details.aspx?id=54616) that win 7 has PS5 too.

**Comment by lord-carlos** [comment]
Elevated permissions got added in #3 by @JKawmi 
I can't really remember if that was needed.

I will test how well it works without when I got some time.

Logo looks good. Thanks for that. And all the other improvements. Extracting with powershell sure would make the script better. Because then you can use it on a new fresh computer.

**Comment by teoxoy** [comment]
Thanks.

Regarding the extraction of archives with powershell, there is a problem: It only works with zips and the nvidia archive is an exe. I tried to just rename it to zip and it works fine if I open it with 7zip but I get an error if I try to extract it using the powershell method. I'm not sure what the solution to this is.

I didn't add the scheduled task parameters to the params because I wanted to ask you if you wanted to split the script in 2 files: one that does the updating and one that creates a scheduled task.

How would you like to go about making the script easier to execute:

- we can make a bat file that just calls the script but then you would have to carry around 2 files ([how to](https://www.howtogeek.com/204088/how-to-use-a-batch-file-to-make-powershell-scripts-easier-to-run/))
- we can encode the script and embed it into a bat file - this way we end up with one file but we would need to make a build process to turn the powershell script into the encoded embeded bat version ([how to](https://dmitrysotnikov.wordpress.com/2008/06/27/powershell-script-in-a-bat-file/))

I like the 2nd way better because it would only produce one file that you can double click and everything would work.

Now that I think about it, removing the scheduled task creation from the script and just adding a section in the readme on how to create one yourself would make more sense because you can do it with one command: `SchTasks /Create /SC DAILY /TN “Nvidia-Updater” /TR “<path_to_script>” /ST 10:00`

I would like to hear your thoughts on all of this.

**Comment by lord-carlos** [comment]
### Extraction
If we have to use 7zip/WinRar for now it's fine.

### Schedular
It's an advanced thing for a minority of users. I think it can either stay as is, or parameter. Or a command on it's own. Though I don't see any harm how it is now. Maybe code clutter? No strong feelings, if you want to remove it go ahead.

### Script easier:
I kinda don't like both options. I can just run the script with `right klick` -> `Run with powershell.`
And I really don't want a build process. Keep it simple. Make it easy to edit.
I guess the bat file would be just for people who don't know how to run a powershell script? With a good readme it might not be needed.

**Comment by teoxoy** [comment]
There are a few issues with the updated readme:
You don't need to download nvidia.ps1 in it's own folder anymore. The script will now download and extract by default in the user appdata/local/temp folder.
There are also some spelling errors.

**Comment by teoxoy** [comment]
Can you give me write access? It's a hassle to keep making changes in my own fork. I can make a new branch and make PRs that way if you like.

**Comment by teoxoy** [comment]
Thanks! I will push some changes to the readme today or tomorrow.

**Comment by teoxoy** [comment]
Also, would you like to change the license to a more permissive one like MIT or ISC?

**Comment by lord-carlos** [comment]
Closing this. Opening another issue to talk about license.
Thanks for all the help.
